spring:
  application:
    name: taco-cloud

  cassandra:
    keyspace-name: taco_cloud
    schema-action: recreate
    local-datacenter: datacenter1

  mongodb:
    host: localhost
    port: 27017
    database: tacoclouddb





