spring:
  application:
    name: taco_cloud

# для h2
#  datasource:
#    url: jdbc:h2:mem:taco_cloud
#    username: sa
#    password:

  datasource:
    url: jdbc:postgresql://localhost:5432/taco_cloud
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver


  cassandra:
    keyspace-name: taco_cloud
    schema-action: recreate
    local-datacenter: datacenter1

  mongodb:
    host: localhost
    port: 27017
    database: tacoclouddb

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect